### ISSUE TITLE
Doesn't work without Groovy or Java 8

### ISSUE THREAD

**Issue by Periclase** [penne12/EasyCalc#2]
HALP!!!

Log:
Your OS:Windows 7
EasyCalc isn't fully supported with your OS. Please paste this into a GitHub iss
ue.

---

 |  ____|               / ____|    | |
 | |__   __ _ ___ _   _| |     __ _| | ___
 |  **| / _` / __| | | | |    / _` | |/ __|
 | |_**| (_| __ \ |_| | |___| (_| | | (__
 |_____|__,_|___/__, |_______,_|_|___|
                   **/ |
                  |_**/
Welcome to EasyCal
Written by Ben of bensites.com
Loading complete
Exception in thread "GUIthread" java.lang.UnsupportedClassVersionError: com/bens
ites/java/EasyCalc/GUI/MainGUI : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at com.bensites.java.EasyCalc.Main$_main_closure1.doCall(Main.groovy:34)

```
    at com.bensites.java.EasyCalc.Main$_main_closure1.doCall(Main.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:
```

90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(C
losureMetaClass.java:278)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1017)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:417)
        at groovy.lang.Closure.run(Closure.java:504)
        at java.lang.Thread.run(Unknown Source)

C:\Users\ACE Student\Desktop\EasyCalc>^A

**Comment by benaubin** [comment]
Sorry about that, looks like it might be an issue of not having Groovy or Java 8.

All tests without Groovy or Java 8 have failed.

All tests with Groovy and Java 8 passed. Could you please try running this on Java 8? If you could, that would be _amazing_!!

Thanks.
